require 'rubygems'
require 'closure-compiler'
require 'fileutils'

def get_files(root, pattern)
	files = []
	
	d = Dir.open(root)

	d.each do |entry|
		if entry !~ /^\..*/ && entry !~ /l7.*/
			entry = root + '/' + entry

			if File.directory?(entry)
				files += get_files(entry, pattern)
			elsif File.file?(entry) && entry =~ pattern
				files << entry
			else
				puts "entry skipped #{entry}"
			end
		end
	end

	files
end

desc "minify javascript"
task :minify do
	rm Dir.glob("./sarah*js")

	lib_root = File.expand_path(".")
  script_names = get_files(lib_root, /.*\.js$/)
	script_names.insert(0, "../../lib_min/l7.min.js")

	compiler = Closure::Compiler.new

  concatted = ""
  script_names.each do |script_name|
		if script_name !~ /.*underscore.*/
			puts "checking: #{script_name}"
			raw = IO.read(script_name)
    	compiler.compile(raw)
			concatted += raw
		end
  end

	minified = compiler.compile(concatted)

	files = [
		{ :in => concatted, :out => "./sarah.debug.js" },
		{ :in => minified, :out => "./sarah.min.js" }
	]

	puts ""
	puts ""

	files.each do |file_info|
		dest = File.expand_path(file_info[:out])
  	File.open(dest, "w") { |file| file.write(file_info[:in]) }
		puts "Created #{dest}"
	end
end

desc "deploy the intro"
task :deploy => :minify do
	deploy_dir = "../sarahDeploy/"
	if Dir.exists?(deploy_dir)
		rm_r deploy_dir
	end

	mkdir deploy_dir

	# copy in
	# *png
	# index.html
	# *css
	# * from resources/
	#
	cp_r "./resources", "#{deploy_dir}resources"

	cp Dir.glob("./*png"), deploy_dir
	cp Dir.glob("./*gif"), deploy_dir
	cp Dir.glob("./*css"), deploy_dir
	cp "./index.html", deploy_dir
	
	# bring in underscore and l7
	cp "../../lib/third/underscore-min.js", deploy_dir

	# and of course sarah itself
	cp "./sarah.min.js", deploy_dir

	# dotcloud yml file
	cp "./dotcloud.yml", deploy_dir

	puts ""
	puts "deployed to #{File.expand_path(deploy_dir)}"
end

