(function(){this.L7=this.L7||{};this.L7.global=this})();
(function(){L7.AnimationFactory=function(a,b){this._owner=a;this._board=b;this._buildStack=[];this._targetStack=[]};L7.AnimationFactory.prototype={_getBoard:function(){return this._board||this._owner.board},_determineTargets:function(a){return a.targets?a.targets:this._owner.getAnimationTargets(a.filter)},_addParentAnimation:function(a,b,c,d){c=new c(d);b&&this._targetStack.push(this._determineTargets(b));this._buildStack.push(c);a(this);this._buildStack.pop();b&&this._targetStack.pop();0===this._buildStack.length?
this._getBoard().addDaemon(c):this._buildStack.last.children.add(c);return c},_addAnimation:function(a,b){a.targets||(a.targets="undefined"!==typeof a.filter?this._owner.getAnimationTargets(a.filter):0<this._targetStack.length?this._targetStack.last:this._owner.getAnimationTargets());var c=new b(a);0===this._buildStack.length?this._getBoard().addDaemon(c):this._buildStack.last.children.add(c);return c},disco:function(a){return this._addAnimation(a,L7.Disco)},shimmer:function(a){return this._addAnimation(a,
L7.Shimmer)},setProperty:function(a){a.duration=0;a.from=a.to=a.value;return this.tween(a)},tween:function(a){return this._addAnimation(a,L7.Tween)},sequence:function(a,b){return this.repeat(1,a,b)},together:function(a,b){var c,d;_.isFunction(a)?d=a:(c=a,d=b);return this._addParentAnimation(d,c,L7.Together)},repeat:function(a,b,c){var d;_.isFunction(b)||(d=b,b=c);return this._addParentAnimation(b,d,L7.Repeat,a)},wait:function(a){return this._addAnimation({duration:a},L7.Wait)},invoke:function(a){return this._addAnimation({func:a},
L7.Invoke)}}})();
(function(){var a=[255,255,255,0.9],b=[255,255,255,0.6];L7.Disco=function(a){_.extend(this,a);this.reset()};L7.Disco.prototype={reset:function(){this.done=!1;this.even=!0;this._discoCount=this._elapsed=0},update:function(a){this.done||(this._elapsed+=a,this._elapsed>=this.rate&&(this.even=!this.even,this._doDisco(this.even,this.targets,this.width),this._elapsed-=this.rate,++this._discoCount),this.done=2<=this._discoCount)},_doDisco:function(c,d,e){for(var g=0;g<d.length;++g){var h=g%e;0===h&&(c=!c);
d[g].overlayColor=c?0===(h&1)?a:b:1===(h&1)?a:b}}}})();Math.linearTween=function(a,b,c,d){return c*a/d+b};Math.easeInQuad=function(a,b,c,d){return c*(a/=d)*a+b};Math.easeOutQuad=function(a,b,c,d){return-c*(a/=d)*(a-2)+b};Math.easeInOutQuad=function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a+b:-c/2*(--a*(a-2)-1)+b};Math.easeInCubic=function(a,b,c,d){return c*(a/=d)*a*a+b};Math.easeOutCubic=function(a,b,c,d){return c*((a=a/d-1)*a*a+1)+b};
Math.easeInOutCubic=function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a*a+b:c/2*((a-=2)*a*a+2)+b};Math.easeInQuart=function(a,b,c,d){return c*(a/=d)*a*a*a+b};Math.easeOutQuart=function(a,b,c,d){return-c*((a=a/d-1)*a*a*a-1)+b};Math.easeInOutQuart=function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a*a*a+b:-c/2*((a-=2)*a*a*a-2)+b};Math.easeInQuint=function(a,b,c,d){return c*(a/=d)*a*a*a*a+b};Math.easeOutQuint=function(a,b,c,d){return c*((a=a/d-1)*a*a*a*a+1)+b};
Math.easeInOutQuint=function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a*a*a*a+b:c/2*((a-=2)*a*a*a*a+2)+b};Math.easeInSine=function(a,b,c,d){return-c*Math.cos(a/d*(Math.PI/2))+c+b};Math.easeOutSine=function(a,b,c,d){return c*Math.sin(a/d*(Math.PI/2))+b};Math.easeInOutSine=function(a,b,c,d){return-c/2*(Math.cos(Math.PI*a/d)-1)+b};Math.easeInExpo=function(a,b,c,d){return 0==a?b:c*Math.pow(2,10*(a/d-1))+b};Math.easeOutExpo=function(a,b,c,d){return a==d?b+c:c*(-Math.pow(2,-10*a/d)+1)+b};
Math.easeInOutExpo=function(a,b,c,d){return 0==a?b:a==d?b+c:1>(a/=d/2)?c/2*Math.pow(2,10*(a-1))+b:c/2*(-Math.pow(2,-10*--a)+2)+b};Math.easeInCirc=function(a,b,c,d){return-c*(Math.sqrt(1-(a/=d)*a)-1)+b};Math.easeOutCirc=function(a,b,c,d){return c*Math.sqrt(1-(a=a/d-1)*a)+b};Math.easeInOutCirc=function(a,b,c,d){return 1>(a/=d/2)?-c/2*(Math.sqrt(1-a*a)-1)+b:c/2*(Math.sqrt(1-(a-=2)*a)+1)+b};
Math.easeInElastic=function(a,b,c,d,e,g){if(0==a)return b;if(1==(a/=d))return b+c;g||(g=0.3*d);e<Math.abs(c)?(e=c,c=g/4):c=g/(2*Math.PI)*Math.asin(c/e);return-(e*Math.pow(2,10*(a-=1))*Math.sin((a*d-c)*2*Math.PI/g))+b};Math.easeOutElastic=function(a,b,c,d,e,g){if(0==a)return b;if(1==(a/=d))return b+c;g||(g=0.3*d);if(e<Math.abs(c))var e=c,h=g/4;else h=g/(2*Math.PI)*Math.asin(c/e);return e*Math.pow(2,-10*a)*Math.sin((a*d-h)*2*Math.PI/g)+c+b};
Math.easeInOutElastic=function(a,b,c,d,e,g){if(0==a)return b;if(2==(a/=d/2))return b+c;g||(g=d*0.3*1.5);if(e<Math.abs(c))var e=c,h=g/4;else h=g/(2*Math.PI)*Math.asin(c/e);return 1>a?-0.5*e*Math.pow(2,10*(a-=1))*Math.sin((a*d-h)*2*Math.PI/g)+b:0.5*e*Math.pow(2,-10*(a-=1))*Math.sin((a*d-h)*2*Math.PI/g)+c+b};Math.easeInBack=function(a,b,c,d,e){void 0==e&&(e=1.70158);return c*(a/=d)*a*((e+1)*a-e)+b};Math.easeOutBack=function(a,b,c,d,e){void 0==e&&(e=1.70158);return c*((a=a/d-1)*a*((e+1)*a+e)+1)+b};
Math.easeInOutBack=function(a,b,c,d,e){void 0==e&&(e=1.70158);return 1>(a/=d/2)?c/2*a*a*(((e*=1.525)+1)*a-e)+b:c/2*((a-=2)*a*(((e*=1.525)+1)*a+e)+2)+b};Math.easeInBounce=function(a,b,c,d){return c-Math.easeOutBounce(d-a,0,c,d)+b};Math.easeOutBounce=function(a,b,c,d){return(a/=d)<1/2.75?c*7.5625*a*a+b:a<2/2.75?c*(7.5625*(a-=1.5/2.75)*a+0.75)+b:a<2.5/2.75?c*(7.5625*(a-=2.25/2.75)*a+0.9375)+b:c*(7.5625*(a-=2.625/2.75)*a+0.984375)+b};
Math.easeInOutBounce=function(a,b,c,d){return a<d/2?0.5*Math.easeInBounce(2*a,0,c,d)+b:0.5*Math.easeOutBounce(2*a-d,0,c,d)+0.5*c+b};(function(){L7.Invoke=function(a){_.extend(this,a);this.reset()};L7.Invoke.prototype={reset:function(){this.done=!1},update:function(){this.done||(this.func(),this.done=!0)}}})();
(function(){L7.Repeat=function(a){this.children=[];this._curCount=this._currentChild=0;this.count=a};L7.Repeat.prototype={reset:function(){this.done=!1;this._curCount=this._currentChild=0;this.children.forEach(function(a){a.reset()})},update:function(){this.done=this._curCount>=this.count;if(!this.done){var a=this.children[this._currentChild];a.update.apply(a,arguments);a.done&&(++this._currentChild,this._currentChild>=this.children.length&&(this._currentChild=0,++this._curCount,this.children.forEach(function(a){a.reset()})));
this.done=this._curCount>=this.count}}}})();
(function(){L7.Shimmer=function(a){_.extend(this,a);this.reset()};L7.Shimmer.prototype={reset:function(){this.done=!1},_initTargets:function(){var a=this.maxAlpha-this.minAlpha,b=this.color||[255,255,255,1];this.targets.forEach(function(c){c.overlayColor=b.slice(0);c.overlayColor[3]=L7.rand(this.minAlpha,this.maxAlpha);c.shimmerRate=Math.floor(L7.rand(this.baseRate-this.baseRate*this.rateVariance,this.baseRate+this.baseRate*this.rateVariance));c.shimmerAlphaPerMilli=a/c.shimmerRate;c.shimmerDirection=
1},this)},update:function(a){this._initted||(this._initTargets(),this._initted=!0);this.done||(this.targets.forEach(function(b){b.overlayColor[3]+=a*b.shimmerAlphaPerMilli*b.shimmerDirection;var c=b.overlayColor[3];c>this.maxAlpha&&(b.shimmerDirection=-1,b.overlayColor[3]=this.maxAlpha);c<this.minAlpha&&(b.shimmerDirection=1,b.overlayColor[3]=this.minAlpha)},this),this.done=!0)}}})();
(function(){L7.Together=function(){this.children=[]};L7.Together.prototype={reset:function(){this.done=!1;this.children.forEach(function(a){a.reset()})},update:function(){if(!this.done){var a=_.toArray(arguments),b=!1;this.children.forEach(function(c){c.update.apply(c,a);c.done||(b=!0)});this.done=!b}}}})();
(function(){var a=0;L7.Tween=function(b){_.extend(this,b);this.reset();this._saveProperty=this.property+"_save_"+a++;this._nonJitteredProperty=this.property+"_nonJittered_"+a++;this._easeFunc=(this._easeFunc=Math[this.easing||"linearTween"])||Math.linearTween};L7.Tween.prototype={reset:function(){this._elapsed=0;this.done=this._elapsed>=this.duration;this._initted=!1},_initTargets:function(){this.targets.forEach(function(a){a[this._saveProperty]=a[this.property];_.isArray(a[this._saveProperty])&&
(a[this._saveProperty]=a[this._saveProperty].slice(0));var c=this.from;_.isUndefined(c)||(_.isArray(c)&&(c=c.slice(0)),a[this.property]=c)},this)},update:function(a){this._initted||(this._initTargets(),this._initted=!0);this.done||(this._elapsed+=a,this._elapsed>this.duration&&(this._elapsed=this.duration,this.done=!0),this.targets.forEach(function(a){this._tween(a)},this),this.done&&this.targets.forEach(function(a){this.restoreAfter&&(a[this.property]=a[this._saveProperty]);delete a[this._saveProperty];
delete a[this._nonJitteredProperty]},this))},_tween:function(a){if(_.isArray(a[this.property]))for(var c=a[this.property],d=0;d<c.length;++d)c[d]=this._tweenValue(this._elapsed,(this.from||a[this._saveProperty])[d],this.to[d],this.duration);else _.isNumber(a[this.property])&&(a[this.property]=this._tweenValue(this._elapsed,this.from,this.to,this.duration))},_tweenValue:function(a,c,d,e){a=this._easeFunc(a,c,d-c,e);this.jitter&&(a+=L7.rand(-this.jitter,this.jitter));return a}}})();
(function(){L7.Wait=function(a){_.extend(this,a);this.reset()};L7.Wait.prototype={reset:function(){this._elapsed=0;this.done=this._elapsed>=this.duration},update:function(a){this.done||(this._elapsed+=a,this._elapsed>this.duration&&(this.done=!0))}}})();
(function(){L7.Actor=function(a){_.extend(this,a);this.ani=new L7.AnimationFactory(this);this.position=this.position||L7.p(0,0);this.shape=this.shape||[[5]];this.keyInputs=this.keyInputs||{};this.pieces=this._createPieces();this._listeners={}};L7.Actor.prototype={getAnimationTargets:function(a){return a?this.pieces.filter(a):this.pieces},on:function(a,b,c){this._listeners[a]||(this._listeners[a]=[]);this._listeners[a].push({handler:b,scope:c})},fireEvent:function(a,b){var c=this._listeners[a];if(_.isArray(c)){var d=
_.toArray(arguments);d.shift();_.each(c,function(a){a.handler.apply(a.scope,d)})}},_getAnchorOffset:function(){var a,b;for(b=0;b<this.shape.length;++b)for(a=0;a<this.shape[b].length;++a)if(this.shape[b][a]===L7.Actor.ANCHOR)return L7.p(a,b);throw Error("shape specified but lacks an anchor");},_getColor:function(a,b){return!this.color?void 0:_.isNumber(this.color[0])?this.color.slice(0):this.color[b][a].slice(0)},_createPieces:function(){for(var a=[],b=this._getAnchorOffset(),c=this.position,d=0;d<
this.shape.length;++d)for(var e=this.shape[d],g=0;g<e.length;++g)if(this.shape[d][g]){var h=L7.p(g,d).delta(b),h=c.add(h),i=this._getColor(g,d),h=new L7.Piece({position:h,color:i,isAnchor:this.shape[d][g]===L7.Actor.ANCHOR,owner:this,scale:_.isNumber(this.scale)?this.scale:1});h.isAnchor&&(this.anchorPiece=h);a.push(h)}return a},_getPiecePositionsAnchoredAt:function(a){var b=a.delta(this.position),c=[];_.each(this.pieces,function(a){c.push(a.position.add(b))});return c},left:function(a){this.goTo(this.position.add(-a,
0))},right:function(a){this.goTo(this.position.add(a,0))},up:function(a){this.goTo(this.position.add(0,-a))},down:function(a){this.goTo(this.position.add(0,a))},goBack:function(){this.goTo(this._lastPosition.clone())},goTo:function(a){if(!this.onGoTo||this.onGoTo(this._getPiecePositionsAnchoredAt(this.position),this._getPiecePositionsAnchoredAt(a),this.board))this._lastPosition=this.position.clone(),this.position=a,this.board&&this.board.moveActor({actor:this,from:this._lastPosition,to:this.position})},
update:function(a,b){var c=!1;_(this.keyInputs).each(function(b,e){if(b.repeat&&L7.Keys.down(e)||L7.Keys.downSince(e,this._lastTimestamp||0))c=!0,("undefined"===typeof b.enabled||b.enabled.call(this))&&b.handler.call(this,a)},this);if(!c&&this.onNoKeyDown)this.onNoKeyDown(a);this._updateTimers(a);this._lastTimestamp=b},_updateTimers:function(a){this.timers&&_.each(this.timers,function(b){if("undefined"===typeof b.enabled||!0===b.enabled||"function"===typeof b.enabled&&b.enabled.call(this))b.elapsed=
b.elapsed||0,b.elapsed+=a,b.elapsed>=b.interval&&(b.elapsed-=b.interval,b.handler.call(this))},this)}};Object.defineProperty(L7.Actor,"ANCHOR",{get:function(){return 5},enumerable:!1})})();
(function(){L7.Board=function(a){_.extend(this,a||{});this.ani=new L7.AnimationFactory(this,this);this.size=new L7.Pair(this.width||0,this.height||0);this.borderWidth=this.borderWidth||0;this.tileSize=this.tileSize||0;this._rows=[];this.tiles=[];for(a=0;a<this.height;++a){for(var b=[],c=0;c<this.width;++c){var d=new L7.Tile({x:c,y:a,board:this});d.color=_.clone(this.defaultTileColor);b.push(d);this.tiles.push(d)}this._rows.push(b)}this.actors=[];this.freeActors=[];this.daemons=[];this.viewportWidth=
Math.min(this.viewportWidth||this.width,this.width);this.viewportHeight=Math.min(this.viewportHeight||this.height,this.height);this.viewportAnchorX=this.viewportAnchor&&this.viewportAnchor.x||0;this.viewportAnchorY=this.viewportAnchor&&this.viewportAnchor.y||0;delete this.viewportAnchor;this._hitManager=new L7.HitManager};L7.Board.prototype={dump:function(){console.log("");console.log("");this._rows.forEach(function(a){var b="";a.forEach(function(a){b=a.getColor()?a.inhabitants.length?b+"a":b+"t":
b+"."});console.log(b)})},actorsOnTeam:function(a){return this.actors.filter(function(b){return b.team===a})},tilesTagged:function(a){return this.tiles.filter(function(b){return b.tag===a})},getAnimationTargets:function(a){return"tiles"===a?this.tiles:"board"===a?[this]:_.isArray(a)?a:this.tiles},destroy:function(){},_clamp:function(a,b,c){return a<b?b:a>=c?c:a},_tileToPixels:function(a){return(this.tileSize+this.borderWidth)*a},scrollCenterOn:function(a){var b=this._tileToPixels(a.x)+this.tileSize/
2,a=this._tileToPixels(a.y)+this.tileSize/2;this.viewport.centerOn(b,a)},scrollY:function(a){this.viewport&&this.viewport.scrollY(this._tileToPixels(a))},scrollX:function(a){this.viewport&&this.viewport.scrollX(this._tileToPixels(a))},scrollXY:function(a,b){this.scrollX(a);this.scrollY(b)},column:function(a){0>a&&(a=this.width+a);for(var b=[],c=0;c<this.height;++c)b.push(this.tileAt(L7.p(a,c)));return b},row:function(a){var b=[];_.each(arguments,function(a){0>a&&(a=this.height+a);for(var d=0;d<this.width;++d)b.push(this.tileAt(L7.p(d,
a)))},this);return b},rect:function(a,b,c,d){for(var e=[],g=b;g<b+d;++g)for(var h=a;h<a+c;++h)e.push(this.tileAt(h,g));return e},query:function(a){var b=[];this.tiles.forEach(function(c){a(c)&&b.push(c)});return b},tileAt:function(a,b){var c=_.isObject(a)?a.x:a,d=_.isNumber(b)?b:a.y;return 0>d||d>=this.height||0>c||c>=this.width?null:this.tiles[d*this.width+c]},tileAtPixels:function(a,b){var c=_.isObject(a)?a.x:a,d=_.isNumber(b)?b:a.y;return this.tileAt(Math.floor(c/(this.tileSize+this.borderWidth)),
Math.floor(d/(this.tileSize+this.borderWidth)))},pixelsForTile:function(a){return L7.p(this._tileToPixels(a.x),this._tileToPixels(a.y))},tileTopInPixels:function(a){return this._tileToPixels(a.y)},tileBottomInPixels:function(a){return this.tileTopInPixels(a)+this.tileSize},each:function(a,b){this.tiles.forEach(a,b)},_addPieces:function(a){a.forEach(function(a){var c=this.tileAt(a.position);c&&c.add(a)},this)},_removePieces:function(a){a.forEach(function(a){var c=this.tileAt(a.position);c&&c.remove(a)},
this)},promote:function(a){a.pieces&&(this._removePieces(a.pieces),this._addPieces(a.pieces))},addActor:function(a){a.pieces&&this._addPieces(a.pieces);this.actors.push(a);a.board=this},addFreeActor:function(a){this.freeActors.push(a);a.board=this},removeFreeActor:function(a){this.freeActors.remove(a);delete a.board},removeActor:function(a){a.pieces&&this._removePieces(a.pieces);this.actors.remove(a);delete a.board},addDaemon:function(a){this.daemons.push(a)},removeDaemon:function(a){if(-1<this.daemons.indexOf(a)&&
a.onRemove)a.onRemove(this);this.daemons.remove(a)},isOutOfBounds:function(a){for(var b=0,c=a.pieces.length;b<c;++b){var d=a.pieces[b].position;if(0>d.x||0>d.y||d.x>=this.width||d.y>=this.height)return!0}return!1},_movePiece:function(a,b){var c=a.position,d=a.position.add(b);(c=this.tileAt(c))&&c.remove(a);(c=this.tileAt(d))&&c.add(a);a.position=d},movePiece:function(a){this._movePiece(a.piece,a.delta||a.to.delta(a.from))},moveActor:function(a){a.actor.pieces.forEach(function(b){this._movePiece(b,
a.delta||a.to.delta(a.from))},this);a.actor.onOutOfBounds&&this.isOutOfBounds(a.actor)&&a.actor.onOutOfBounds.call(a.actor)},update:function(a,b){this.actors.forEach(function(c){c.update(a,b)});this.freeActors.forEach(function(c){c.update(a,b)});this.daemons.forEach(function(c){c.update(a,b,this)},this);this._hitManager.detectHits(this.tiles)},render:function(a,b,c,d){var c=c+(this.offsetX||0),d=d+(this.offsetY||0),e=this.borderWidth,a=this.tileSize,g=(0>d?Math.ceil:Math.floor)(d/(a+e)),h=-d%(a+e),
i,u=Math.min(this._rows.length,Math.ceil((d+b.canvas.height)/(a+e))),l=(0>c?Math.ceil:Math.floor)(c/(a+e)),k=-c%(a+e),n,w=Math.min(this._rows[0].length,Math.ceil((c+b.canvas.width)/(a+e))),q,m,v,r=[];for(i=g;i<u;++i)if(0<=i){v=this._rows[i];for(n=l;n<w;++n)if(0<=n&&(q=v[n],m=q.getColor()))o=q.getScale(),_.isNumber(o)||(o=1),1!==o&&(r.push(q),m=q.getColor(!0),o=1),m&&(this.borderFill&&(b.fillStyle=this.borderFill,b.fillRect((n-l)*(a+e)+k,(i-g)*(a+e)+h,a+2*e,e),b.fillRect((n-l)*(a+e)+k,(i-g)*(a+e)+
h+a+e,a+2*e,e),b.fillRect((n-l)*(a+e)+k,(i-g)*(a+e)+h,e,a+2*e),b.fillRect((n-l)*(a+e)+k+a+e,(i-g)*(a+e)+h,e,a+2*e)),b.fillStyle=m,m=Math.round(a*o),o=a/2-m/2,b.fillRect((n-l)*(a+e)+e+o+k,(i-g)*(a+e)+e+o+h,m,m))}r.sort(function(a,c){return a.scale-c.scale});for(i=0;i<r.length;++i){q=r[i];var o=q.getScale();if(m=q.getColor())b.fillStyle=m,m=Math.round(a*o),o=a/2-m/2,b.fillRect((q.x-l)*(a+e)+e+o+k,(q.y-g)*(a+e)+e+o+h,m,m)}for(i=0;i<this.freeActors.length;++i)if(e=this.freeActors[i],m=L7.Color.toCssString(e.color))b.fillStyle=
m,b.fillRect(e.position.x-c,e.position.y-d,a,a)}}})();
(function(){L7.HitManager=function(){};L7.HitManager.prototype={detectHits:function(a){a.forEach(function(a){this._detectTileHits(a)},this)},_detectTileHits:function(a){a.each(function(b){_.isObject(b.owner)&&_.isObject(b.owner.hitDetection)&&("undefined"===typeof b.owner.hitDetection.enabled||b.owner.hitDetection.enabled.call(b.owner))&&_.each(b.owner.hitDetection,function(c,d){a.tag===d&&c.call(b.owner,a,a);a.each(function(e){e!==b&&e.owner&&e.owner.team===d&&c.call(b.owner,a,e.owner)},this)},this)},
this)}}})();
(function(){L7.ParallaxBoard=function(a){_.extend(this,a);this.boards=this.boards||[];this.boards.forEach(function(a){if(!_.isNumber(a.parallaxRatio))throw Error("ParallaxBoard: given a board that lacks a parallax ratio");})};L7.ParallaxBoard.prototype={update:function(){var a=_.toArray(arguments);this.boards.forEach(function(b){b.update.apply(b,a)})},render:function(a,b,c,d,e){this.boards.forEach(function(g){g.render(a,b,c*g.parallaxRatio,d*g.parallaxRatio,e)})}};Object.defineProperty(L7.ParallaxBoard.prototype,"viewport",
{get:function(){return this.viewport},set:function(a){this.boards.forEach(function(b){b.viewport=a})},enumerable:!0})})();(function(){L7.Piece=function(a){_.extend(this,a||{})};L7.Piece.prototype={render:function(){this.sprite&&(this.sprite.overlay=this._overlay,this.sprite.render.apply(this.sprite,arguments))}};Object.defineProperty(L7.Piece.prototype,"overlay",{get:function(){return this._overlay},set:function(a){this._overlay=a},enumerable:!0})})();
(function(){L7.Tile=function(a){a=a||{};if(!_.isNumber(a.x))throw Error("Tile: x is required");if(!_.isNumber(a.y))throw Error("Tile: y is required");this.x=a.x;this.y=a.y;this.color=a.color;this.scale=a.scale;this.board=a.board;this.inhabitants=_.clone(a.inhabitants||[]);this.position=L7.p(this.x,this.y)};L7.Tile.prototype={at:function(a){return this.inhabitants[a]},each:function(a,b){this.inhabitants.forEach(a,b)},add:function(a){this.inhabitants.push(a)},remove:function(a){this.inhabitants.remove(a)},
has:function(a){return this.tag===a?!0:this.inhabitants.some(function(b){return b.team===a||b.owner&&b.owner.team===a})},hasOther:function(a,b){return this.tag===a?!0:this.inhabitants.some(function(c){return c.team===a||c.owner&&c.owner.team===a&&c.owner!==b})},getColor:function(a){var b=[];this.color&&b.push(this.color);!a&&0<this.inhabitants.length&&this.inhabitants.last.color&&b.push(this.inhabitants.last.color);this.overlayColor&&b.push(this.overlayColor);if(0<b.length)return a=L7.Color.composite.apply(L7.Color,
b),L7.Color.toCssString(a)},getColorOld:function(){var a;if(0===this.inhabitants.length||!this.inhabitants[this.inhabitants.length-1].color)a=this.color;else if(a=this.inhabitants[this.inhabitants.length-1],L7.Color.isOpaque(a.color)||!this.color)a=a.color;else{var b=this.color.slice(0);a=L7.Color.composite(b,a.color)}this.overlayColor&&(a=!a||L7.Color.isOpaque(this.overlayColor)?this.overlayColor:L7.Color.composite(a.slice(0),this.overlayColor));if(a)return L7.Color.toCssString(a)},getScale:function(){return 0===
this.inhabitants.length||!this.inhabitants.last.color?this.scale:this.inhabitants.last.scale},up:function(){return this.board&&this.board.tileAt(this.position.up())},down:function(){return this.board&&this.board.tileAt(this.position.down())},left:function(){return this.board&&this.board.tileAt(this.position.left())},right:function(){return this.board&&this.board.tileAt(this.position.right())}};Object.defineProperty(L7.Tile.prototype,"count",{get:function(){return this.inhabitants.length},enumerable:!0})})();
(function(){function a(a){var a=a.substring(1),b=a.substring(0,2),e=a.substring(2,4),a=a.substring(4,6);return result=[parseInt(b,16),parseInt(e,16),parseInt(a,16),1]}L7.Color={toCssString:function(a){return 3===a.length?"rgb("+Math.round(a[0])+","+Math.round(a[1])+","+Math.round(a[2])+")":"rgba("+Math.round(a[0])+","+Math.round(a[1])+","+Math.round(a[2])+","+a[3]+")"},isBuiltInString:function(a){return"string"!==typeof a?!1:b.hasOwnProperty(a.toLowerCase())},isHexString:function(a){if("string"!==
typeof a||"#"!==a[0]||7!==a.length)return!1;for(var a=a.toUpperCase(),b=1,e=a.length;b<e;++b){var g=a[b];if("0">g||"F"<g)return!1}return!0},isOpaque:function(a){return this.isHexString(a)||this.isBuiltInString(a)?!0:(a=this.toArray(a))&&1===a[3]},isRgbString:function(a){return"string"!==typeof a||10>a.length||0!==a.indexOf("rgb")||")"!==a[a.length-1]||"("!==a[3]&&"("!==a[4]?!1:!0},toArray:function(c){if(_.isArray(c)&&4===c.length)return c;if(this.isHexString(c))return a(c);if(this.isBuiltInString(c))return a(b[c]);
if(this.isRgbString(c)){for(var d=c.indexOf("("),e=[],c=c.substring(d+1).split(","),d=0,g=c.length;d<g;++d)e.push(parseFloat(c[d]));3===e.length&&e.push(1);return e}},fromArrayToHex:function(a,b){for(var e="#",g=b&&b.includeAlpha&&4===a.length?4:3,h=0;h<g;++h){var i=a[h].toString(16);2>i.length&&(i="0"+i);e+=i}return e.toUpperCase()},composite:function(a){for(var b=this.toArray(arguments[0]).slice(0),e=1;e<arguments.length;++e){var g=b,h=this.toArray(arguments[e]),i=h[3],u=g[3],l=1-i,k=void 0,n=void 0;
for(k=0,n=g.length-1;k<n;++k)g[k]=Math.round(h[k]*i+g[k]*u*l);g[3]=(g[3]+h[3])/2}return b},fromFloats:function(a,b,e,g){return[Math.round(255*a),Math.round(255*b),Math.round(255*e),g]}};var b={aliceblue:"#F0F8FF",antiquewhite:"#FAEBD7",aqua:"#00FFFF",aquamarine:"#7FFFD4",azure:"#F0FFFF",beige:"#F5F5DC",bisque:"#FFE4C4",black:"#000000",blanchedalmond:"#FFEBCD",blue:"#0000FF",blueviolet:"#8A2BE2",brown:"#A52A2A",burlywood:"#DEB887",cadetblue:"#5F9EA0",chartreuse:"#7FFF00",chocolate:"#D2691E",coral:"#FF7F50",
cornflowerblue:"#6495ED",cornsilk:"#FFF8DC",crimson:"#DC143C",cyan:"#00FFFF",darkblue:"#00008B",darkcyan:"#008B8B",darkgoldenrod:"#B8860B",darkgray:"#A9A9A9",darkgrey:"#A9A9A9",darkgreen:"#006400",darkkhaki:"#BDB76B",darkmagenta:"#8B008B",darkolivegreen:"#556B2F",darkorange:"#FF8C00",darkorchid:"#9932CC",darkred:"#8B0000",darksalmon:"#E9967A",darkseagreen:"#8FBC8F",darkslateblue:"#483D8B",darkslategray:"#2F4F4F",darkslategrey:"#2F4F4F",darkturquoise:"#00CED1",darkviolet:"#9400D3",deeppink:"#FF1493",
deepskyblue:"#00BFFF",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1E90FF",firebrick:"#B22222",floralwhite:"#FFFAF0",forestgreen:"#228B22",fuchsia:"#FF00FF",gainsboro:"#DCDCDC",ghostwhite:"#F8F8FF",gold:"#FFD700",goldenrod:"#DAA520",gray:"#808080",grey:"#808080",green:"#008000",greenyellow:"#ADFF2F",honeydew:"#F0FFF0",hotpink:"#FF69B4",indianred:"#CD5C5C",indigo:"#4B0082",ivory:"#FFFFF0",khaki:"#F0E68C",lavender:"#E6E6FA",lavenderblush:"#FFF0F5",lawngreen:"#7CFC00",lemonchiffon:"#FFFACD",lightblue:"#ADD8E6",
lightcoral:"#F08080",lightcyan:"#E0FFFF",lightgoldenrodyellow:"#FAFAD2",lightgray:"#D3D3D3",lightgrey:"#D3D3D3",lightgreen:"#90EE90",lightpink:"#FFB6C1",lightsalmon:"#FFA07A",lightseagreen:"#20B2AA",lightskyblue:"#87CEFA",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#B0C4DE",lightyellow:"#FFFFE0",lime:"#00FF00",limegreen:"#32CD32",linen:"#FAF0E6",magenta:"#FF00FF",maroon:"#800000",mediumaquamarine:"#66CDAA",mediumblue:"#0000CD",mediumorchid:"#BA55D3",mediumpurple:"#9370D8",mediumseagreen:"#3CB371",
mediumslateblue:"#7B68EE",mediumspringgreen:"#00FA9A",mediumturquoise:"#48D1CC",mediumvioletred:"#C71585",midnightblue:"#191970",mintcream:"#F5FFFA",mistyrose:"#FFE4E1",moccasin:"#FFE4B5",navajowhite:"#FFDEAD",navy:"#000080",oldlace:"#FDF5E6",olive:"#808000",olivedrab:"#6B8E23",orange:"#FFA500",orangered:"#FF4500",orchid:"#DA70D6",palegoldenrod:"#EEE8AA",palegreen:"#98FB98",paleturquoise:"#AFEEEE",palevioletred:"#D87093",papayawhip:"#FFEFD5",peachpuff:"#FFDAB9",peru:"#CD853F",pink:"#FFC0CB",plum:"#DDA0DD",
powderblue:"#B0E0E6",purple:"#800080",red:"#FF0000",rosybrown:"#BC8F8F",royalblue:"#4169E1",saddlebrown:"#8B4513",salmon:"#FA8072",sandybrown:"#F4A460",seagreen:"#2E8B57",seashell:"#FFF5EE",sienna:"#A0522D",silver:"#C0C0C0",skyblue:"#87CEEB",slateblue:"#6A5ACD",slategray:"#708090",slategrey:"#708090",snow:"#FFFAFA",springgreen:"#00FF7F",steelblue:"#4682B4",tan:"#D2B48C",teal:"#008080",thistle:"#D8BFD8",tomato:"#FF6347",turquoise:"#40E0D0",violet:"#EE82EE",wheat:"#F5DEB3",white:"#FFFFFF",whitesmoke:"#F5F5F5",
yellow:"#FFFF00",yellowgreen:"#9ACD32"}})();
(function(){L7.LevelLoader=function(a){_.extend(this,a);this.width=a.image.width;this.height=a.image.height};L7.LevelLoader.prototype={load:function(){for(var a=_.extend(this.boardConfig,{width:this.width,height:this.height}),b=new L7.Board(a),c={},a=this._getData(),d=0;d<a.length;d+=4){var e=this._extractColor(a,d),g=this.legend[e];if(g){var h=this._getPosition(d);if(g.hasOwnProperty("constructor")){var i=_.extend({},g.config||{},{position:h});_.isArray(g.constructor)||(g.constructor=[g.constructor]);
g.constructor.forEach(function(a){a=new a(i);c[e]=c[e]||[];c[e].push(a);b.addActor(a)})}g.tag&&(b.tileAt(h).tag=g.tag);g.color&&(b.tileAt(h).color=g.color)}}return{board:b,actors:c}},_getData:function(){var a=document.createElement("canvas");a.width=this.width;a.height=this.height;a=a.getContext("2d");a.drawImage(this.image,0,0);return a.getImageData(0,0,this.width,this.height).data},_extractColor:function(a,b){for(var c=[],d=b;d<b+3;++d)c.push(a[d]);return L7.Color.fromArrayToHex(c)},_getPosition:function(a){a=
Math.floor(a/4);return L7.p(a%this.width,Math.floor(a/this.width))}}})();
(function(){var a=1E3*(1/60);window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};L7.Game=function(a){a="function"!==typeof a.render&&"function"!==typeof a.update?a:{width:a.width*(a.tileSize+a.borderWidth)+a.borderWidth,height:a.height*(a.tileSize+a.borderWidth)+a.borderWidth,board:a};_.extend(this,a);_.bindAll(this,"_doFrame");
this.viewport=new L7.Viewport(this);this.board&&(this.board.viewport=this.viewport);this.container=this.container||document.body;this.canvas=this._createCanvas();this.delays=[];var c=this;L7.global.addEventListener("blur",function(){console.log("blurred");delete c._lastTimestamp})};L7.Game.prototype={_createCanvas:function(){var a=document.createElement("canvas");a.width=this.viewport.width;a.height=this.viewport.height;a.style.imageRendering="-webkit-optimize-contrast";this.container.appendChild(a);
return a},go:function(){delete this._lastTimestamp;this._doFrame(Date.now())},after:function(a,c){this.delays.add({remaining:a,handler:c})},replaceBoard:function(a){this.board&&this.board.destroy&&this.board.destroy();this.board=a;this.board.viewport=this.viewport;this.viewport.reset()},_updateDelays:function(a){var c=[];this.delays.forEach(function(d){d.remaining-=a;0>=d.remaining&&(d.handler.call(d.scope,this),c.push(d))},this);c.forEach(function(a){this.delays.remove(a)},this)},_pause:function(){var a=
this.canvas.getContext("2d");a.save();a.fillStyle="rgba(255,255,255,0.5)";a.fillRect(0,0,this.canvas.width,this.canvas.height);a.restore()},_doFrame:function(b){var c=b-(this._lastTimestamp||b);this._lastTimestamp=b;for(var d=c;0<d;){var e=Math.min(a,d);this._updateDelays(e);this.board.update(e,b);d-=e}d=this.canvas.getContext("2d");d.clearRect(0,0,this.canvas.width,this.canvas.height);this.board.render(c,d,this.viewport.anchorX,this.viewport.anchorY,b);this.paused||requestAnimationFrame(this._doFrame)}};
Object.defineProperty(L7.Game.prototype,"paused",{get:function(){return this._paused},set:function(a){var c=this._paused;this._paused=a;c!==a&&(a?this._pause():this.go())}})})();
(function(){L7.Keys={arrows:{37:"left",38:"up",39:"right",40:"down"},init:function(){this._hook=window;this._keyDownListener=_.bind(this._onKeyDown,this);this._hook.addEventListener("keydown",this._keyDownListener,!1);this._keyUpListener=_.bind(this._onKeyUp,this);this._hook.addEventListener("keyup",this._keyUpListener,!1);this._downKeys={}},_getCharacter:function(a){return this.arrows[a.toString()]||String.fromCharCode(a).toLowerCase()},_onKeyDown:function(a){a=this._getCharacter(a.keyCode);this._downKeys[a]||
(this._downKeys[a]=Date.now())},_onKeyUp:function(a){delete this._downKeys[this._getCharacter(a.keyCode)]},down:function(a){return void 0!==this._downKeys[a]},downSince:function(a,b){return this.down(a)&&this._downKeys[a]>b}}})();
(function(){L7.Viewport=function(a){a=a||{};_.extend(this,a);_.isUndefined(this.preventOverscroll)&&(this.preventOverscroll=!1);this.anchorX=a.initialAnchor&&a.initialAnchor.x||0;this.anchorY=a.initialAnchor&&a.initialAnchor.y||0;this.width=this.width||100;this.height=this.height||100};L7.Viewport.prototype={scrollY:function(a){this.anchorY+=a},scrollX:function(a){this.anchorX+=a},centerOn:function(a,b){var c=a.y||b;this.anchorX=Math.floor((a.x||a)-this.width/2);this.anchorY=Math.floor(c-this.height/
2)},reset:function(){this.anchorY=this.anchorX=0}}})();
(function(){L7.Pair=function(a,b){this._a=a||0;this._b=b||0};L7.Pair.prototype={clone:function(){return L7.p(this.x,this.y)},equals:function(a){return a?a===this||a._a===this._a&&a._b==this._b||a.x===this._a&&a.y==this._b||a.width==this._a&&a.height==this._b:!1},up:function(){return L7.p(this.x,this.y-1)},left:function(){return L7.p(this.x-1,this.y)},right:function(){return L7.p(this.x+1,this.y)},down:function(){return L7.p(this.x,this.y+1)},add:function(a,b){return L7.p(this.x+("number"===typeof a.x?
a.x:a||0),this.y+("number"===typeof a.y?a.y:b||0))},subtract:function(a,b){x="number"===typeof a.x?a.x:a||0;y="number"===typeof a.y?a.y:b||0;return L7.p(this.x-x,this.y-y)},negate:function(){return L7.p(-this.x,-this.y)},multiply:function(a){return L7.p(this.x*a,this.y*a)},dot:function(a){return this.x*a.x+this.y*a.y},length:function(){return Math.sqrt(this.dot(this))},normalize:function(){return this.multiply(1/this.length())},distanceFrom:function(a){a=this.delta(a);return Math.sqrt(a.dot(a))},
toString:function(){return"["+this._a+","+this._b+"]"}};L7.Pair.prototype.delta=L7.Pair.prototype.subtract;Object.defineProperty(L7.Pair.prototype,"width",{get:function(){return this._a}});Object.defineProperty(L7.Pair.prototype,"height",{get:function(){return this._b}});Object.defineProperty(L7.Pair.prototype,"x",{get:function(){return this._a},set:function(a){this._a=a}});Object.defineProperty(L7.Pair.prototype,"y",{get:function(){return this._b},set:function(a){this._b=a}});L7.s=function(a,b){return new L7.Pair(a,
b)};L7.p=L7.s;L7.sr=function(a,b){return new L7.Pair(Math.round(a),Math.round(b))};L7.pr=L7.sr})();
(function(){function a(){return L7.rand(-1,1,!0)}var b=0;L7.ParticleSystem=function(a){_.extend(this,a);this._particles=[];this.id=b++;this._particleTeam="particle-"+this.id;for(a=0;a<this.totalParticles;++a)this._particles.push(new L7.Actor({position:this.position.clone(),team:this._particleTeam}));this._particleCount=this._particleIndex=this._emitCounter=this._elapsed=0;this.active=this.active||!1};L7.ParticleSystem.prototype={onRemove:function(a){a.actorsOnTeam(this._particleTeam).forEach(function(b){a.removeActor(b)},
this);this._addedActors=!1},_isFull:function(){return this._particleCount===this.totalParticles},_initParticle:function(c){c.rx=this.position.x+this.posVar.x*a();c.ry=this.position.y+this.posVar.y*a();var b;b=this.angle+this.angleVar*a();b=(b||0)*Math.PI/180;b=L7.p(Math.cos(b),Math.sin(b));var e=this.speed+this.speedVar*a();b=b.multiply(e);c.dir=b;c.radialAccel=this.radialAccel+this.radialAccelVar*a();c.radialAccel&&(c.radialAccel=0);c.tangentialAccel=this.tangentialAccel+this.tangentialAccelVar*
a();c.tangentialAccel||(c.tangentialAccel=0);b=this.life+this.lifeVar*a();c.life=Math.max(0,b);b=[this.startColor[0]+this.startColorVar[0]*a(),this.startColor[1]+this.startColorVar[1]*a(),this.startColor[2]+this.startColorVar[2]*a(),this.startColor[3]+this.startColorVar[3]*a()];e=[this.endColor[0]*this.endColorVar[0]*a(),this.endColor[1]*this.endColorVar[1]*a(),this.endColor[2]*this.endColorVar[2]*a(),this.endColor[3]*this.endColorVar[3]*a()];c.color=b;c.pieces[0].color=b;c.deltaColor=[(e[0]-b[0])/
c.life,(e[1]-b[1])/c.life,(e[2]-b[2])/c.life,(e[3]-b[3])/c.life];_.isUndefined(this.startSize)?(c.size=1,c.deltaSize=0):(b=this.startSize+this.startSizeVar*a(),b=Math.max(0,b),c.size=b,_.isUndefined(this.endSize)?c.deltaSize=0:(e=this.endSize+this.endSizeVar*a(),c.deltaSize=(e-b)/c.life))},_addParticle:function(){if(this._isFull())return!1;this._initParticle(this._particles[this._particleCount]);++this._particleCount;return!0},update:function(a,b,e){if(this.active){a/=1E3;if(this.emissionRate){b=
1/this.emissionRate;for(this._emitCounter+=a;!this._isFull()&&this._emitCounter>b;)this._addParticle(),this._emitCounter-=b}this._elapsed+=a;this.active=this._elapsed<this.duration;for(this._particleIndex=0;this._particleIndex<this._particleCount;)this._updateParticle(this._particles[this._particleIndex],a,this._particleIndex);this._updateBoard(e)}},_updateParticle:function(a,b,e){if(0<a.life){var e=L7.p(),g=L7.p(),h=L7.p();if(a.position.x!==this.position.x||a.position.y!==this.position.y)g=L7.p(a.rx,
a.ry).normalize();h=g.clone();g.x*=a.radialAccel;g.y*=a.radialAccel;var i=h.x;h.x=-h.y;h.y=i;h.x*=a.tangentialAccel;h.y*=a.tangentialAccel;e.x=g.x+h.x+this.gravity.x;e.y=g.y+h.y+this.gravity.y;e.x*=b;e.y*=b;a.dir.x+=e.x;a.dir.y+=e.y;e.x=a.dir.x*b;e.y=a.dir.y*b;a.rx+=e.x;a.ry+=e.y;a.goTo(L7.pr(a.rx,a.ry));a.color[0]+=a.deltaColor[0]*b;a.color[1]+=a.deltaColor[1]*b;a.color[2]+=a.deltaColor[2]*b;a.color[3]+=a.deltaColor[3]*b;a.size+=a.deltaSize*b;a.size=Math.max(0,a.size);a.pieces[0].scale=a.size;a.life-=
b;++this._particleIndex}else a=this._particles[e],this._particles[e]=this._particles[this._particleCount-1],this._particles[this._particleCount-1]=a,--this._particleCount},_updateBoard:function(a){window.ps=this;this._addedActors||(this._particles.forEach(function(b){a.addActor(b)}),this._addedActors=!0);for(var b=L7.p(-1,-1),e=this._particleCount;e<this._particles.length;++e)this._particles[e].goTo(b)}}})();
(function(){function a(b,c,d){if(b===c)return 0!==b||1/b==1/c;if(null==b||null==c)return b===c;b._chain&&(b=b._wrapped);c._chain&&(c=c._wrapped);if(b.isEqual&&f.isFunction(b.isEqual))return b.isEqual(c);if(c.isEqual&&f.isFunction(c.isEqual))return c.isEqual(b);var e=l.call(b);if(e!=l.call(c))return!1;switch(e){case "[object String]":return b==""+c;case "[object Number]":return b!=+b?c!=+c:0==b?1/b==1/c:b==+c;case "[object Date]":case "[object Boolean]":return+b==+c;case "[object RegExp]":return b.source==
c.source&&b.global==c.global&&b.multiline==c.multiline&&b.ignoreCase==c.ignoreCase}if("object"!=typeof b||"object"!=typeof c)return!1;for(var g=d.length;g--;)if(d[g]==b)return!0;d.push(b);var g=0,h=!0;if("[object Array]"==e){if(g=b.length,h=g==c.length)for(;g--&&(h=g in b==g in c&&a(b[g],c[g],d)););}else{if("constructor"in b!="constructor"in c||b.constructor!=c.constructor)return!1;for(var t in b)if(k.call(b,t)&&(g++,!(h=k.call(c,t)&&a(b[t],c[t],d))))break;if(h){for(t in c)if(k.call(c,t)&&!g--)break;
h=!g}}d.pop();return h}var b=this,c=b._,d={},e=Array.prototype,g=Object.prototype,h=e.slice,i=e.concat,u=e.unshift,l=g.toString,k=g.hasOwnProperty,n=e.forEach,w=e.map,q=e.reduce,m=e.reduceRight,v=e.filter,r=e.every,o=e.some,z=e.indexOf,C=e.lastIndexOf,g=Array.isArray,F=Object.keys,A=Function.prototype.bind,f=function(a){return new s(a)};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=f),exports._=f):"function"===typeof define&&define.amd?define("underscore",
function(){return f}):b._=f;f.VERSION="1.2.3";var p=f.each=f.forEach=function(a,b,c){if(null!=a)if(n&&a.forEach===n)a.forEach(b,c);else if(a.length===+a.length)for(var e=0,f=a.length;e<f&&!(e in a&&b.call(c,a[e],e,a)===d);e++);else for(e in a)if(k.call(a,e)&&b.call(c,a[e],e,a)===d)break};f.map=function(a,b,c){var d=[];if(null==a)return d;if(w&&a.map===w)return a.map(b,c);p(a,function(a,j,e){d[d.length]=b.call(c,a,j,e)});return d};f.reduce=f.foldl=f.inject=function(a,b,c,d){var e=2<arguments.length;
null==a&&(a=[]);if(q&&a.reduce===q)return d&&(b=f.bind(b,d)),e?a.reduce(b,c):a.reduce(b);p(a,function(a,j,f){e?c=b.call(d,c,a,j,f):(c=a,e=!0)});if(!e)throw new TypeError("Reduce of empty array with no initial value");return c};f.reduceRight=f.foldr=function(a,b,c,d){var e=2<arguments.length;null==a&&(a=[]);if(m&&a.reduceRight===m)return d&&(b=f.bind(b,d)),e?a.reduceRight(b,c):a.reduceRight(b);var g=f.toArray(a).reverse();d&&!e&&(b=f.bind(b,d));return e?f.reduce(g,b,c,d):f.reduce(g,b)};f.find=f.detect=
function(a,b,c){var d;D(a,function(a,j,e){if(b.call(c,a,j,e))return d=a,!0});return d};f.filter=f.select=function(a,b,c){var d=[];if(null==a)return d;if(v&&a.filter===v)return a.filter(b,c);p(a,function(a,j,e){b.call(c,a,j,e)&&(d[d.length]=a)});return d};f.reject=function(a,b,c){var d=[];if(null==a)return d;p(a,function(a,j,e){b.call(c,a,j,e)||(d[d.length]=a)});return d};f.every=f.all=function(a,b,c){var e=!0;if(null==a)return e;if(r&&a.every===r)return a.every(b,c);p(a,function(a,j,f){if(!(e=e&&
b.call(c,a,j,f)))return d});return e};var D=f.some=f.any=function(a,b,c){b||(b=f.identity);var e=!1;if(null==a)return e;if(o&&a.some===o)return a.some(b,c);p(a,function(a,j,f){if(e||(e=b.call(c,a,j,f)))return d});return!!e};f.include=f.contains=function(a,b){return null==a?!1:z&&a.indexOf===z?-1!=a.indexOf(b):D(a,function(a){return a===b})};f.invoke=function(a,b){var c=h.call(arguments,2);return f.map(a,function(a){return(b.call?b||a:a[b]).apply(a,c)})};f.pluck=function(a,b){return f.map(a,function(a){return a[b]})};
f.max=function(a,b,c){if(!b&&f.isArray(a))return Math.max.apply(Math,a);if(!b&&f.isEmpty(a))return-Infinity;var d={computed:-Infinity};p(a,function(a,j,e){j=b?b.call(c,a,j,e):a;j>=d.computed&&(d={value:a,computed:j})});return d.value};f.min=function(a,b,c){if(!b&&f.isArray(a))return Math.min.apply(Math,a);if(!b&&f.isEmpty(a))return Infinity;var d={computed:Infinity};p(a,function(a,j,e){j=b?b.call(c,a,j,e):a;j<d.computed&&(d={value:a,computed:j})});return d.value};f.shuffle=function(a){var b=[],c;
p(a,function(a,d){0==d?b[0]=a:(c=Math.floor(Math.random()*(d+1)),b[d]=b[c],b[c]=a)});return b};f.sortBy=function(a,b,c){return f.pluck(f.map(a,function(a,d,j){return{value:a,criteria:b.call(c,a,d,j)}}).sort(function(a,b){var c=a.criteria,d=b.criteria;return c<d?-1:c>d?1:0}),"value")};f.groupBy=function(a,b){var c={},d=f.isFunction(b)?b:function(a){return a[b]};p(a,function(a,b){var j=d(a,b);(c[j]||(c[j]=[])).push(a)});return c};f.sortedIndex=function(a,b,c){c||(c=f.identity);for(var d=0,e=a.length;d<
e;){var g=d+e>>1;c(a[g])<c(b)?d=g+1:e=g}return d};f.toArray=function(a){return!a?[]:a.toArray?a.toArray():f.isArray(a)?h.call(a):f.isArguments(a)?h.call(a):f.values(a)};f.size=function(a){return f.toArray(a).length};f.first=f.head=function(a,b,c){return null!=b&&!c?h.call(a,0,b):a[0]};f.initial=function(a,b,c){return h.call(a,0,a.length-(null==b||c?1:b))};f.last=function(a,b,c){return null!=b&&!c?h.call(a,Math.max(a.length-b,0)):a[a.length-1]};f.rest=f.tail=function(a,b,c){return h.call(a,null==b||
c?1:b)};f.compact=function(a){return f.filter(a,function(a){return!!a})};f.flatten=function(a,b){return f.reduce(a,function(a,c){if(f.isArray(c))return a.concat(b?c:f.flatten(c));a[a.length]=c;return a},[])};f.without=function(a){return f.difference(a,h.call(arguments,1))};f.uniq=f.unique=function(a,b,c){var c=c?f.map(a,c):a,d=[];f.reduce(c,function(c,e,g){if(0==g||(!0===b?f.last(c)!=e:!f.include(c,e)))c[c.length]=e,d[d.length]=a[g];return c},[]);return d};f.union=function(){return f.uniq(f.flatten(arguments,
!0))};f.intersection=f.intersect=function(a){var b=h.call(arguments,1);return f.filter(f.uniq(a),function(a){return f.every(b,function(b){return 0<=f.indexOf(b,a)})})};f.difference=function(a){var b=f.flatten(h.call(arguments,1));return f.filter(a,function(a){return!f.include(b,a)})};f.zip=function(){for(var a=h.call(arguments),b=f.max(f.pluck(a,"length")),c=Array(b),d=0;d<b;d++)c[d]=f.pluck(a,""+d);return c};f.indexOf=function(a,b,c){if(null==a)return-1;var d;if(c)return c=f.sortedIndex(a,b),a[c]===
b?c:-1;if(z&&a.indexOf===z)return a.indexOf(b);for(c=0,d=a.length;c<d;c++)if(c in a&&a[c]===b)return c;return-1};f.lastIndexOf=function(a,b){if(null==a)return-1;if(C&&a.lastIndexOf===C)return a.lastIndexOf(b);for(var c=a.length;c--;)if(c in a&&a[c]===b)return c;return-1};f.range=function(a,b,c){1>=arguments.length&&(b=a||0,a=0);for(var c=arguments[2]||1,d=Math.max(Math.ceil((b-a)/c),0),e=0,f=Array(d);e<d;)f[e++]=a,a+=c;return f};var E=function(){};f.bind=function(a,b){var c,d;if(a.bind===A&&A)return A.apply(a,
h.call(arguments,1));if(!f.isFunction(a))throw new TypeError;d=h.call(arguments,2);return c=function(){if(!(this instanceof c))return a.apply(b,d.concat(h.call(arguments)));E.prototype=a.prototype;var e=new E,f=a.apply(e,d.concat(h.call(arguments)));return Object(f)===f?f:e}};f.bindAll=function(a){var b=h.call(arguments,1);0==b.length&&(b=f.functions(a));p(b,function(b){a[b]=f.bind(a[b],a)});return a};f.memoize=function(a,b){var c={};b||(b=f.identity);return function(){var d=b.apply(this,arguments);
return k.call(c,d)?c[d]:c[d]=a.apply(this,arguments)}};f.delay=function(a,b){var c=h.call(arguments,2);return setTimeout(function(){return a.apply(a,c)},b)};f.defer=function(a){return f.delay.apply(f,[a,1].concat(h.call(arguments,1)))};f.throttle=function(a,b){var c,d,e,g,h,i=f.debounce(function(){h=g=!1},b);return function(){c=this;d=arguments;e||(e=setTimeout(function(){e=null;h&&a.apply(c,d);i()},b));g?h=!0:a.apply(c,d);i();g=!0}};f.debounce=function(a,b){var c;return function(){var d=this,e=arguments;
clearTimeout(c);c=setTimeout(function(){c=null;a.apply(d,e)},b)}};f.once=function(a){var b=!1,c;return function(){if(b)return c;b=!0;return c=a.apply(this,arguments)}};f.wrap=function(a,b){return function(){var c=i.apply([a],arguments);return b.apply(this,c)}};f.compose=function(){var a=arguments;return function(){for(var b=arguments,c=a.length-1;0<=c;c--)b=[a[c].apply(this,b)];return b[0]}};f.after=function(a,b){return 0>=a?b():function(){if(1>--a)return b.apply(this,arguments)}};f.keys=F||function(a){if(a!==
Object(a))throw new TypeError("Invalid object");var b=[],c;for(c in a)k.call(a,c)&&(b[b.length]=c);return b};f.values=function(a){return f.map(a,f.identity)};f.functions=f.methods=function(a){var b=[],c;for(c in a)f.isFunction(a[c])&&b.push(c);return b.sort()};f.extend=function(a){p(h.call(arguments,1),function(b){for(var c in b)void 0!==b[c]&&(a[c]=b[c])});return a};f.defaults=function(a){p(h.call(arguments,1),function(b){for(var c in b)null==a[c]&&(a[c]=b[c])});return a};f.clone=function(a){return!f.isObject(a)?
a:f.isArray(a)?a.slice():f.extend({},a)};f.tap=function(a,b){b(a);return a};f.isEqual=function(b,c){return a(b,c,[])};f.isEmpty=function(a){if(f.isArray(a)||f.isString(a))return 0===a.length;for(var b in a)if(k.call(a,b))return!1;return!0};f.isElement=function(a){return!!(a&&1==a.nodeType)};f.isArray=g||function(a){return"[object Array]"==l.call(a)};f.isObject=function(a){return a===Object(a)};f.isArguments=function(a){return"[object Arguments]"==l.call(a)};f.isArguments(arguments)||(f.isArguments=
function(a){return!(!a||!k.call(a,"callee"))});f.isFunction=function(a){return"[object Function]"==l.call(a)};f.isString=function(a){return"[object String]"==l.call(a)};f.isNumber=function(a){return"[object Number]"==l.call(a)};f.isNaN=function(a){return a!==a};f.isBoolean=function(a){return!0===a||!1===a||"[object Boolean]"==l.call(a)};f.isDate=function(a){return"[object Date]"==l.call(a)};f.isRegExp=function(a){return"[object RegExp]"==l.call(a)};f.isNull=function(a){return null===a};f.isUndefined=
function(a){return void 0===a};f.noConflict=function(){b._=c;return this};f.identity=function(a){return a};f.times=function(a,b,c){for(var d=0;d<a;d++)b.call(c,d)};f.escape=function(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};f.mixin=function(a){p(f.functions(a),function(b){G(b,f[b]=a[b])})};var H=0;f.uniqueId=function(a){var b=H++;return a?a+b:b};f.templateSettings={evaluate:/<%([\s\S]+?)%>/g,
interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};f.template=function(a,b){var c=f.templateSettings,c="var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(c.escape,function(a,b){return"',_.escape("+b.replace(/\\'/g,"'")+"),'"}).replace(c.interpolate,function(a,b){return"',"+b.replace(/\\'/g,"'")+",'"}).replace(c.evaluate||null,function(a,b){return"');"+b.replace(/\\'/g,"'").replace(/[\r\n\t]/g," ")+";__p.push('"}).replace(/\r/g,
"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+"');}return __p.join('');",d=new Function("obj","_",c);return b?d(b,f):function(a){return d.call(this,a,f)}};var s=function(a){this._wrapped=a};f.prototype=s.prototype;var B=function(a,b){return b?f(a).chain():a},G=function(a,b){s.prototype[a]=function(){var a=h.call(arguments);u.call(a,this._wrapped);return B(b.apply(f,a),this._chain)}};f.mixin(f);p("pop,push,reverse,shift,sort,splice,unshift".split(","),function(a){var b=e[a];s.prototype[a]=function(){b.apply(this._wrapped,
arguments);return B(this._wrapped,this._chain)}});p(["concat","join","slice"],function(a){var b=e[a];s.prototype[a]=function(){return B(b.apply(this._wrapped,arguments),this._chain)}});s.prototype.chain=function(){this._chain=!0;return this};s.prototype.value=function(){return this._wrapped}}).call(this);
(function(){L7.FadeBase=function(a){_.extend(this,a);this.elapsed=0;this.color&&(this.color=L7.Color.toArray(this.color))};L7.FadeBase.prototype={update:function(a,b){this.elapsed+=a;var c=this.elapsed/this.duration;this.updateColor(this.color,c);if(1<c&&this.onComplete)this.onComplete(this);this.board.update(a,b)},render:function(a,b,c,d,e){this.board.render(a,b,c,d,e);b.save();b.fillStyle=L7.Color.toCssString(this.color);b.fillRect(0,0,b.canvas.width,b.canvas.height);b.restore()}};Object.defineProperty(L7.FadeBase.prototype,
"viewport",{set:function(a){this._viewport=a;this.board&&(this.board.viewport=a)},get:function(){return this._viewport},enumerable:!0})})();(function(){L7.FadeIn=function(a){a.color=a.from;L7.FadeBase.call(this,a)};L7.FadeIn.prototype=new L7.FadeBase;L7.FadeIn.prototype.updateColor=function(a,b){a[3]=1-b}})();(function(){L7.FadeOut=function(a){a.color=a.to;L7.FadeBase.call(this,a)};L7.FadeOut.prototype=new L7.FadeBase;L7.FadeOut.prototype.updateColor=function(a,b){a[3]=b}})();
(function(){L7.FadeOutIn=function(a){_.extend(this,a);_.bindAll(this,"_onFadeOutComplete","_onFadeInComplete");this.delegate=new L7.FadeOut({board:this.fromBoard,to:this.color,duration:this.duration/2,onComplete:this._onFadeOutComplete})};L7.FadeOutIn.prototype={_onFadeOutComplete:function(){this.delegate=new L7.FadeIn({board:this.toBoard,from:this.color,duration:this.duration/2,onComplete:this._onFadeInComplete});this.delegate.viewport=this.viewport},_onFadeInComplete:function(){if(this.onComplete)this.onComplete();
else this.game&&this.game.replaceBoard(this.toBoard)},update:function(){this.delegate.update.apply(this.delegate,arguments)},render:function(){this.delegate.render.apply(this.delegate,arguments)}};Object.defineProperty(L7.FadeOutIn.prototype,"viewport",{set:function(a){this._viewport=a;this.delegate&&(this.delegate.viewport=a)},get:function(){return this._viewport},enumerable:!0})})();
(function(){"undefined"===typeof Array.prototype.add&&(Array.prototype.add=function(a){this.push(a);return this});"undefined"===typeof Array.prototype.remove&&(Array.prototype.remove=function(a){a=this.indexOf(a);0<=a&&this.splice(a,1);return this});"undefined"===typeof Array.prototype.last&&Object.defineProperty(Array.prototype,"last",{get:function(){return this[this.length-1]},enumerable:!1});"undefined"===typeof Array.prototype.first&&Object.defineProperty(Array.prototype,"first",{get:function(){return this[0]},
enumerable:!1})})();(function(){L7.rand=function(a,b,c){_.isUndefined(c)&&(c=!1);var d=_.isNumber(b)?a:0,a=_.isNumber(b)?b:a,b=Math.random()*(a-d)+d;return d===(d|0)&&a===(a|0)&&!c?Math.floor(b):b}})();L7.Keys.init();var board=new L7.Board({tileSize:10,borderWidth:2,width:30,height:30,borderFill:"black"});board.tiles.forEach(function(a){a.color=[20,20,20,1]});
var sunSystem=new L7.ParticleSystem({totalParticles:300,duration:Infinity,gravity:L7.p(),centerOfGravity:L7.p(),angle:90,angleVar:360,radialAccel:0,radialAccelVar:0,position:L7.p(board.width/2,board.height/2),posVar:L7.p(),life:0.5,lifeVar:0.5,speed:10,speedVar:5,emissionRate:350,startColor:L7.Color.fromFloats(0.9,0.6,0.12,1),startColorVar:[10,10,3,0],endColor:[0,0,0,1],endColorVar:[0,0,0,0],active:!0}),galaxySystem=new L7.ParticleSystem({totalParticles:200,duration:Infinity,gravity:L7.p(),centerOfGravity:L7.p(),
angle:90,angleVar:360,speed:15,speedVar:5,radialAccel:-20,radialAccelVar:0,tangentialAccel:20,tangentialAccelVar:0,position:L7.p(board.width/2,board.height/2),posVar:L7.p(),life:3,lifeVar:1,emissionRate:50,startColor:L7.Color.fromFloats(0.12,0.25,0.76,1),startColorVar:[0,0,0,0],endColor:[0,0,0,1],endColorVar:[0,0,0,0],active:!0,startSize:2.5,startSizeVar:0.5}),fireworksSystem=new L7.ParticleSystem({totalParticles:90,duration:Infinity,gravity:L7.p(0,-90),centerOfGravity:L7.p(),angle:-90,angleVar:20,
speed:30,speedVar:5,radialAccel:0,radialAccelVar:0,tangentialAccel:0,tangentialAccelVar:0,position:L7.p(board.width/2,board.height),posVar:L7.p(),life:1.3,lifeVar:0.2,emissionRate:90/1.3,startColor:L7.Color.fromFloats(0.5,0.5,0.5,1),startColorVar:L7.Color.fromFloats(0.5,0.5,0.5,0.1),endColor:L7.Color.fromFloats(0.1,0.1,0.1,0.2),endColorVar:L7.Color.fromFloats(0.1,0.1,0.1,0.2),active:!0}),fireSystem=new L7.ParticleSystem({totalParticles:200,duration:Infinity,gravity:L7.p(),centerOfGravity:L7.p(),angle:-90,
angleVar:10,speed:24,speedVar:10,radialAccel:0,radialAccelVar:0,tangentialAccel:0,tangentialAccelVar:0,position:L7.p(board.width/2,board.height-4),posVar:L7.p(2,1),life:1.2,lifeVar:0.25,emissionRate:200,startColor:L7.Color.fromFloats(0.76,0.25,0.12,1),startColorVar:[0,0,0,0],endColor:[0,0,0,0],endColorVar:[0,0,0,0],active:!0}),meteorSystem=new L7.ParticleSystem({totalParticles:100,duration:Infinity,gravity:L7.p(-200,-200),centerOfGravity:L7.p(),angle:90,angleVar:360,speed:13,speedVar:5,radialAccel:0,
radialAccelVar:0,tangentialAccel:0,tangentialAccelVar:0,position:L7.p(board.width/2,board.height/2),posVar:L7.p(),life:0.7,lifeVar:0.2,emissionRate:100,startColor:L7.Color.fromFloats(0.3,0.5,0.8,1),startColorVar:L7.Color.fromFloats(0,0,0.2,0.1),endColor:[0,0,0,1],endColorVar:[0,0,0,0],startSize:3,startSizeVar:0.5,endSize:0.5,endSizeVar:0,active:!0}),snowSystem=new L7.ParticleSystem({totalParticles:50,duration:Infinity,gravity:L7.p(0,1),centerOfGravity:L7.p(),angle:90,angleVar:10,speed:5,speedVar:1,
radialAccel:0,radialAccelVar:2,tangentialAccel:0,tangentialAccelVar:2,position:L7.p(board.width/2,0),posVar:L7.p(board.width/2,0),life:6,lifeVar:2,emissionRate:10,startColor:L7.Color.fromFloats(1,1,1,1),startColorVar:[0,0,0,0],endColor:L7.Color.fromFloats(1,1,1,0),endColorVar:[0,0,0,0],active:!0}),rainSystem=new L7.ParticleSystem({totalParticles:80,duration:Infinity,gravity:L7.p(100,-10),centerOfGravity:L7.p(),angle:90,angleVar:5,speed:100,speedVar:30,radialAccel:0,radialAccelVar:1,tangentialAccel:0,
tangentialAccelVar:1,position:L7.p(board.width/2,0),posVar:L7.p(board.width/2,0),life:1.8,lifeVar:0,emissionRate:40,startColor:L7.Color.fromFloats(0.7,0.8,1,1),startColorVar:[0,0,0,0],endColor:L7.Color.fromFloats(0.7,0.8,1,1),endColorVar:[0,0,0,0],active:!0}),daemons=[sunSystem,galaxySystem,fireworksSystem,fireSystem,meteorSystem,snowSystem,rainSystem],daemonIndex=0;
function setNextSystem(a){var b=daemons[daemonIndex];daemonIndex+=a;0>daemonIndex&&(daemonIndex=daemons.length-1);daemonIndex>=daemons.length&&(daemonIndex=0);board.removeDaemon(b);board.addDaemon(daemons[daemonIndex])}board.addActor(new L7.Actor({keyInputs:{left:{repeat:!1,handler:function(){setNextSystem(-1)}},right:{repeat:!1,handler:function(){setNextSystem(1)}}},position:L7.p(-1,-1)}));setNextSystem(0);
var game=new L7.Game({board:board,container:document.getElementById("particleContainer"),width:board.width*(board.tileSize+board.borderWidth)+board.borderWidth,height:board.height*(board.tileSize+board.borderWidth)+board.borderWidth});game._doFrame(Date.now());game.paused=!0;game.canvas.onclick=function(){game.paused=!game.paused};
